### ISSUE TITLE
So many errors need help

### ISSUE THREAD

**Issue by rahuldotbiz** [draftbox-co/gatsby-ghost-novela-starter#2]
## Plz see this log i am getting som many errors. Thank You so much for thi amazing template

C:\Users\gamer\try-ghost>gatsby develop
success open and validate gatsby-configs - 0.456s
warning Plugin @draftbox-co/gatsby-plugin-css-variables is not compatible with your gatsby version 2.21.1 - It requires gatsby@2.20.24
error Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-plugin-typescript@2.8.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-react-helmet@3.6.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-sharp@2.10.1 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-transformer-sharp@2.8.0 is using the API "unstable_shouldOnCreateNode" which was introduced in gatsby@2.24.80.
- The plugin gatsby-plugin-mdx@1.6.0 is using the API "unstable_shouldOnCreateNode" which was introduced in gatsby@2.24.80.
- The plugin gatsby-plugin-mdx@1.6.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-source-filesystem@2.7.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-emotion@4.5.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-feed@2.9.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.

Some of the following may help fix the error(s):

- npm install gatsby@^2.25.0
- Rename "unstable_shouldOnCreateNode" -> "onCreateNode"
- Rename "unstable_shouldOnCreateNode" -> "onCreateNode"
success load plugins - 4.329s
success onPreInit - 0.141s
success initialize cache - 0.012s
success copy gatsby files - 0.253s
success onPreBootstrap - 0.067s
success createSchemaCustomization - 0.024s
warning The gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 2.551s
warning Plugin `@draftbox-co/gatsby-ghost-novela-theme` tried to define the GraphQL type `GhostPost`, which has already been defined by the plugin `gatsby-source-ghost`.
warning Plugin `@draftbox-co/gatsby-ghost-novela-theme` tried to define the GraphQL type `GhostPage`, which has already been defined by the plugin `gatsby-source-ghost`.
success building schema - 1.203s

Config rootPath not set, using basePath instead => /

Config basePath /

Config authorsPath /authors

error There was an error in your GraphQL query:

Cannot query field "readingTime" on type "GhostPost".

If you don't expect "readingTime" to exist on the type "GhostPost" it is most likely a typo.
However, if you expect "readingTime" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "readingTime" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPost":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error There was an error in your GraphQL query:

Cannot query field "mdx" on type "GhostPost".

If you don't expect "mdx" to exist on the type "GhostPost" it is most likely a typo.
However, if you expect "mdx" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "mdx" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPost":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error There was an error in your GraphQL query:

Cannot query field "readingTime" on type "GhostPage".

If you don't expect "readingTime" to exist on the type "GhostPage" it is most likely a typo.
However, if you expect "readingTime" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "readingTime" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPage":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error There was an error in your GraphQL query:

Cannot query field "mdx" on type "GhostPage".

If you don't expect "mdx" to exist on the type "GhostPage" it is most likely a typo.
However, if you expect "mdx" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "mdx" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPage":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error There was an error in your GraphQL query:

Cannot query field "localFeatureImage" on type "GhostPage".

If you don't expect "localFeatureImage" to exist on the type "GhostPage" it is most likely a typo.
However, if you expect "localFeatureImage" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "localFeatureImage" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPage":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error There was an error in your GraphQL query:

Cannot query field "localFeatureImage" on type "GhostPage".

If you don't expect "localFeatureImage" to exist on the type "GhostPage" it is most likely a typo.
However, if you expect "localFeatureImage" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "localFeatureImage" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "GhostPage":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
TypeError: Cannot read property 'articles' of undefined
    at Object.module.exports [as createPages] (C:\Users\gamer\try-ghost\node_modules\@draftbox-co\gatsby-ghost-novela-theme\src\gatsby\node\createPages.js:108:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Creating articles page

success createPages - 0.153s
warning Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property instead. Please check the `on` configuration for "#pageComponents.inactive".
warning Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property instead. Please check the `on` configuration for "#pageComponents.inactive".
warning Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property instead. Please check the `on` configuration for "#pageComponents.inactive".
warning Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property instead. Please check the `on` configuration for "#pageComponents.inactive".
success createPagesStatefully - 0.287s
success onPreExtractQueries - 0.002s
success update schema - 0.058s
success extract queries from components - 2.217s
warning The GraphQL query in the non-page component "C:/Users/gamer/try-ghost/node_modules/@draftbox-co/gatsby-ghost-novela-theme/src/templates/article.template.amp.tsx" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out requires - 0.383s
success write out redirect data - 0.113s
success onPostBootstrap - 0.195s
⠀
info bootstrap finished - 19.626 s
⠀
success run queries - 0.191s - 5/5 26.24/s
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in style
    in HTML
⠀
You can now view gatsby-ghost-novela-starter in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 8.329s

**Comment by thandaanda** [comment]
Hi @rahxuls,

This starter should work out-of-box without any modifications. Can you send us a minimal reproducible repo to help us understand the issue.

**Comment by rahuldotbiz** [comment]
As ghost CMS is paid. Is there any way i can use this template?

**Comment by rahuldotbiz** [comment]
I will know the issue about this ASAP. But can you plz tell me the above
thing.

**Comment by thandaanda** [comment]
Hi @rahxuls,

You can use the https://www.digitalpress.blog/ for free Ghost hosting or if you want to try out Draftbox CMS - you can visit us at https://draftbox.co
